### ISSUE TITLE
Item from Arachnus faces the wrong way

### ISSUE THREAD

**Issue by dyceron** [randovania/open-samus-returns-rando#10]
If the item that Arachnus drops is a tank, it will face to the right. This does not affect Major Items because they rotate and are viewable from all angles.

![image](https://user-images.githubusercontent.com/38679103/207984349-27269112-06cf-4cf7-b2bd-49b3177adbf3.png)

**Comment by dyceron** [comment]
So it looks like the rotation of the pickup depends on what direction Arachnus is facing when it dies. So in this case, it died on the right side facing left, so now the pickup points to the background (left side death points to foreground)
![image](https://github.com/randovania/open-samus-returns-rando/assets/38679103/58890a4b-0813-452d-8161-44d565aa8f08)

**Comment by ThanatosGit** [comment]
Is it worth changing it after the cutscene? While arachnus dies and the pickup spawns, it will probably needs a exefs patch because it just inherits the rotation from arachnus. Changing it after the cutscene is a low hanging fruit.

https://github.com/randovania/open-samus-returns-rando/assets/117127188/bc9360bf-65c4-446a-8616-9ac3d5271759

**Comment by dyceron** [comment]
I don't really like how that looks so yeah

**Comment by ThanatosGit** [comment]
Ok, then I mark it as `won't fix` in my head 😛

**Comment by dyceron** [comment]
It's peetry much only an issue for tanks and progressive models. The rest are OK enough

**Comment by ThanatosGit** [comment]
could add a check on every frame during the arachnus fight. same for rotating progressives but don't know if i like that

**Comment by Miepee** [comment]
Imo, having the sudden transition after cutscene is better than it always looking in the wrong direction.

**Comment by dyceron** [comment]
@ThanatosGit can you make a pr for this since you did it once before? 😛

**Comment by ThanatosGit** [comment]
`second-bad-arachnus-fix`: https://github.com/randovania/open-samus-returns-rando/issues/10#issuecomment-1960076448 -> https://github.com/randovania/open-samus-returns-rando/compare/second-bad-arachnus-fix

or `bad-arachnus-fix`: (see attachment) -> https://github.com/randovania/open-samus-returns-rando/compare/bad-arachnus-fix


https://github.com/randovania/open-samus-returns-rando/assets/117127188/4d9daa29-cb33-4238-b0b4-21c7b60930e7

**Comment by dyceron** [comment]
I'll fine with option 2. On the outside, it is seamless.
