### ISSUE TITLE
Model issues

### ISSUE THREAD

**Issue by ThanatosGit** [randovania/open-samus-returns-rando#126]
Played a little bit through my first seed
1. This one is not animating: 
![image](https://github.com/randovania/open-samus-returns-rando/assets/117127188/ad5d0e83-8bc4-4afe-8113-7d464d4124f5)

2. Because Aeion abilities are exported with also granting aeion energy, they have two items in the patcher file. Two items are considered a multi item pickup `patch_multi_item_pickup` and skippng the whole fx part from `patch_single_item_pickup`...it is just a orb / nothing item in the game.

**Comment by dyceron** [comment]
1. Odd that it's not animating
2. Do we move the aeion stuff to multi pickup instead?

**Comment by ThanatosGit** [comment]
1. NVM. It's a more randovania thing. Aeion Tanks are exported as `ITEM_MAX_SPECIAL_ENERGY` but need to be `ITEM_AEION_TANKS`
2. It sounds better to me to make part of `patch_model`. This also decides if it's using the multi model updater component, where the FX doesn't work anyways.

**Comment by dyceron** [comment]
Yeah the next pr will be fixing up all the item ids

**Comment by ThanatosGit** [comment]
For pbs and supers it's already pushed to my branch

**Comment by ThanatosGit** [comment]
Should both be done from the patcher side and also from rdv side if the pr's get merged
