### ISSUE TITLE
Collecting a pickup restarts the area music

### ISSUE THREAD

**Issue by dyceron** [randovania/open-samus-returns-rando#133]
Not a game changer but is noticeable and not how the vanilla game works. Collecting an item from a Metroid does not restart the music (unsure)

**Comment by ThanatosGit** [comment]
You could play around with this line https://github.com/randovania/open-samus-returns-rando/blob/0181f1862d9922b610bb3b7e067a8541702740ad/open_samus_returns_rando/files/templates/randomizer_item_template.lua#L7C19-L7C19

No idea what the params are. There was also a "different play sounds" function iirc.
