### ISSUE TITLE
Certain Metroids do not get disabled/drop an item

### ISSUE THREAD

**Issue by dyceron** [randovania/open-samus-returns-rando#135]
Sometimes the Metroid function is called and sometimes its not. Problematic Metroids found in testing:

- area2b: Gamma_001
- area6: Gamma_002

**Comment by ThanatosGit** [comment]
For the record: Gammas have two different death animations. `death` and `airdeath`. The patcher needs to be adjusted for `airdeath` to also change the `GenerateADN` to our custom function `RemoveMetroid`
