### ISSUE TITLE
Sync Randovania with patcher and vice versa + modify main item logic

### ISSUE THREAD

**Issue by ThanatosGit** [randovania/open-samus-returns-rando#140]
Patcher was written that e.g. PBs are exported with 
```
            "resources": [
                [
                    {
                        "item_id": "ITEM_WEAPON_POWER_BOMB_MAX",
                        "quantity": 5
                    }
                ]
            ],
```
but randovania exports:
```
            "resources": [
                [
                    {
                        "item_id": "ITEM_WEAPON_POWER_BOMB_MAX",
                        "quantity": 1
                    },
                    {
                        "item_id": "ITEM_RANDO_LOCKED_PBS",
                        "quantity": 5
                    },
                ]
            ],
```
similiar for supers.

`ITEM_WEAPON_POWER_BOMB` should be introduced. That way we can easily check if we have main item and don't need to it via `ITEM_WEAPON_POWER_BOMB_MAX` shenanigans. In retrospect it was a bad idea from me but luckily it should be very easy and only very few changes in code.

**Comment by dyceron** [comment]
Should we also take this time to rename the tanks to be more traditional, like "ITEM_POWER_BOMB_TANK"?

**Comment by ThanatosGit** [comment]
Sounds good
