### ISSUE TITLE
Multi-Room Gammas don't end properly

### ISSUE THREAD

**Issue by dyceron** [randovania/open-samus-returns-rando#144]
It looks like the multi-room Gammas never properly die. The Metroid counter does change, the item is given, and the Metroid does not respawn, but the radar never ends and the post Gamma Spawn Groups never activate.

**Comment by ThanatosGit** [comment]
Radar is tied to the spawn groups. I guess we need to disable them all.
Post gamma setup is tied to a blackboard property e.g. see https://github.com/randovania/open-samus-returns-rando/blob/4e7d6983087a17e07666d267d9bb405f10ad7a8c/open_samus_returns_rando/files/levels/s033_area3b.lua#L499-L512
