### ISSUE TITLE
Change beam door covers to be properly double sided

### ISSUE THREAD

**Issue by dyceron** [randovania/open-samus-returns-rando#17]
Non-Beam Covers (Missile, Super, Power Bomb) can be opened on either side of the door, even on the side you aren't supposed to access. They have the proper collision, but do not visually appear on the wrong side.

Beam Door Covers on the other hand can be opened from the backside, but the collision/actor does not transfer over. In order to open them from the wrong side, you have to place Samus up against the door and shoot backwards through the door at certain angles to open the lock. There are situations where opening from the back might be impossible, so it might be best to change every beam door cover to be easily accessible from both sides and have the proper visuals.

Changing all door covers to be easily accessible from both sides would be a good QoL.

**Comment by dyceron** [comment]
From my minimal messing around, I was able to duplicate non-beam covers, which then requires double the missiles/supers (not pbs) to open. Maybe there's a way to copy the fx/texture to the backside.

Beam covers will be more involved as just copying the cover does not remove it when broken. Would need to link these up somehow.

**Comment by ThanatosGit** [comment]
Double the missiles? I know a game with the same issue...

**Comment by dyceron** [comment]
Yeah I don't want to have to do this since those covers technically do work, but just aren't visible. Fixing beam covers is a much higher priority since they don't work as you'd expect.
