### ISSUE TITLE
Allow for shuffled Missile Launcher

### ISSUE THREAD

**Issue by dyceron** [randovania/open-samus-returns-rando#227]
Currently, if you try to start without Missiles, you are unable to use Supers at all. It seems like the HUD doesn't want to update when `R` is being held. This is evident if you use PBs but don't have Missiles. They do work, but when you Morph, there's no change to show the PB icon. Maybe the solution to this is to update the HUD fully regardless.

![image](https://github.com/randovania/open-samus-returns-rando/assets/38679103/4c5e9336-faa8-4d5a-b43d-0e69424d846d)

**Comment by ThanatosGit** [comment]
https://github.com/randovania/open-samus-returns-rando/pull/239
