### ISSUE TITLE
Make "Powerbomb seeds" less awkward

### ISSUE THREAD

**Issue by ThanatosGit** [randovania/open-samus-returns-rando#229]
Some collected ideas:
- Remove PB vulnerability from bomb blocks to not superseed bombs
- Increase the drop rate of PBs
- Add more refill stations
- Refill at save stations (like it is also done at the ship)

**Comment by henriquegemignani** [comment]
My idea was a setting to just disable logical uses of pb where bombs work.
This would just make pbs less likely to happen earlier than bombs.

(or progressive bombs -> pbs? )

**Comment by dyceron** [comment]
I'd love to change the block vulnerabilities themselves with a config, but for the life of me I can't find where the weaknesses are stored

**Comment by ThanatosGit** [comment]
Do we want to something else from here or is it fine now?
Finguring out where the vulnerabilities are stored is a seperate issue and I don't even know if it is a good idea to do that.

**Comment by dyceron** [comment]
We can close this since we have the other issue. If we do find out where the vulnerabilities are stored it would be a configurable change anyway and not forced.
