### ISSUE TITLE
Find cause and fix infinite loading

### ISSUE THREAD

**Issue by ThanatosGit** [randovania/open-samus-returns-rando#230]
😥

**Comment by dyceron** [comment]
I can confirm this also causes an infinite load for me. This is nuts.

**Comment by ThanatosGit** [comment]
Haven't found the real cause but looks like the game just doing stupid things with the lua when / after dying. #251 changed to lua from ascii version to byte versions which (hopefully) makes it impossible in a normal playthrough to occur.
Teste are still as comment in the lua. Test should be redone when there is a lot of lua added. Potentially we could still save a lot of bytes later by using string identifier for messages and save them in the language files.
