### ISSUE TITLE
Use Chozo Seals for hints

### ISSUE THREAD

**Issue by dyceron** [randovania/open-samus-returns-rando#24]
Either for Major Items or DNA in the area

Make them require x amount of DNA to use, using a global DNA amount

**Comment by dyceron** [comment]
One idea is to just leave the vanilla DNA amounts but use a global DNA count, so each seal requires the same amount of DNA it normally does.

For example, Area 1 needs 4 DNA to use the unlock the seal, so 4 DNA could be required to access the hint.

DNA Amounts per Area: 
- Surface: 1
- Area 1: 4
- Area 2: 7
- Area 3: 10
- Area 4 1, 3
- Area 5: 8
- Area 6: 1, 1
- Area 7: 3

**Comment by Miepee** [comment]
If you end up going with that, then they shouldn't give hints to DNA IMO.
I personally feel like it'd be nicer to just go the dread approach, and make them give you the hint instantly when you visit them, without a prerequisite of collecting past DNA.

**Comment by dyceron** [comment]
That's a fair point. I do want to repurpose these so hints are good, but I also want some use for DNA besides end game goal.

**Comment by duncathan** [comment]
could give one dread-style hint on first visit, and a more precise hint (for another item) when returning the dna? I quite like the idea of dna retaining its use at chozo seals

**Comment by Miepee** [comment]
A thing to note here though:
The way that artifacts/dna usually work with this, is that you already start with TOTAL_DNA - DNA_REQUIRED. So you'd effectively have free access to most of those.
If you end up not starting with that dna, then you likely won't be able to access most of these special hints, as there isn't that much of a reason to go collect more DNA than what's required to beat game.

**Comment by dyceron** [comment]
There is this line when you try to use a seal with no DNA which could be modified `Metroid DNA data is required to unlock this seal. No Metroid DNA is detected.`

**Comment by duncathan** [comment]
> A thing to note here though:
> The way that artifacts/dna usually work with this, is that you already start with TOTAL_DNA - DNA_REQUIRED. So you'd effectively have free access to most of those.
> If you end up not starting with that dna, then you likely won't be able to access most of these special hints, as there isn't that much of a reason to go collect more DNA than what's required to beat game.

that's simply a convention due to it being convenient. could just as easily start with nothing and change the requirement

**Comment by dyceron** [comment]
Another idea: have the Seals check for Metroid count instead of DNA, so it's almost the same as vanilla but slightly different. In vanilla, if you return some dna, it shows the general location of one Metroid. This could be another incentive to fight Metroids besides just items. If going this route, I'd have the required amounts be lower than vanilla.
