### ISSUE TITLE
Adjust respawn timers for blocks in tunnels

### ISSUE THREAD

**Issue by dyceron** [randovania/open-samus-returns-rando#295]
All shot blocks in tunnels could just be changed to never respawn, which would help remove softlocks without bombs or pbs. Bomb blocks could also be changed but these might need to looked at in a case by case basis depending on what might be affected logically.

**Comment by dyceron** [comment]
No longer interested in this.

**Comment by Miepee** [comment]
Closing, see closed referenced PR for discussion.
If someone wants this, they should come up with a way where it doesn't break the puzzles, while still benefitting beginners.
