### ISSUE TITLE
Wall07 and Pickup disappear if leaving the Diggernaut Arena early

### ISSUE THREAD

**Issue by dyceron** [randovania/open-samus-returns-rando#304]
If you leave the Diggernaut Arena and don't pick up the item or break the wall first, re-entering the cc will have both of them deleted, and the wall is now indestructible. Either find a way to keep both from disappearing or prevent exiting the room. This can only happen in Door Lock Rando.

**Comment by ThanatosGit** [comment]
We should just keep the door closed. Otherwise we also need to mess with the combat model, giving pbs back etc. when leaving mid fight.
Will also be a nice cursed soft lock if you kill diggernaut but missing a reqirement for the doors after the fight :)

**Comment by ThanatosGit** [comment]
Hmmm we could lock the door during the fight but after the fight we need to unlock it, which means you can still leave without destroying diggernaut properly with a pb and then your path is blocked again as already described.

IMO options are:
1. Remove DoorManicMinerBot from being randomized at all
2. Use a special case to change this door only on the right side (depends on the logic db and if it could break something there)
3. Lock the door and somehow only unlock it when the blocking wall / diggernaut is destroyed.

**Comment by dyceron** [comment]
I like option 2. Should be doable I feel

**Comment by dyceron** [comment]
> I like option 2. Should be doable I feel

Actually yes this could definitely be doable since one-way doors already exist (this being one of them). There's other doors which are one way like the one in A4 with the heat room heading to the Zeta, and also the Plasma Door in A5 and A4, etc. I assume you'd have to exclude in the DB on the one side, and then exclude the door in the patcher somehow?

**Comment by ThanatosGit** [comment]
We just skipping to change the door to doorpowerpower and keep it as doorclosedpower.

Hmmm is there a doorclosedcharge? Otherwise it would be the only unsupported door.

Afaik in randovania door lock is always on both sides, so we would actually make sure that it is never logically required to go through this door in reverse.

**Comment by dyceron** [comment]
The door is already `doorclosedcharge`
![image](https://github.com/randovania/open-samus-returns-rando/assets/38679103/b7689f18-1a8d-4974-aa4d-09e311c7a48f)

**Comment by ThanatosGit** [comment]
Haha, ok. I just tested stuff in the this branch, so it was always a power door and already forgot about the vanilla door.
Then it doesn't look like an issue. It's either doorclosedpower with a shield thing or doorclosedcharge.

**Comment by dyceron** [comment]
Yeah if we can keep the closed part in the arena while still having a randomized shield on the other side that's the ideal scenario. I did consider the idea of just having it two way so you could possibly fight Diggernaut and leave without PBs, but that would require fixing the other things.

**Comment by ThanatosGit** [comment]
Just don't know how the db looks like.
It would be required that there is no path back from the diggernaut area through this door.

**Comment by dyceron** [comment]
It currently connects back to the right door, but that can easily be changed.
