### ISSUE TITLE
More fun with disappearing items due to PBs (Area 5 - Phase Drift Trial West)

### ISSUE THREAD

**Issue by ThanatosGit** [randovania/open-samus-returns-rando#308]
Should be fixed before stable release in RDV.
See: https://discord.com/channels/914291389293027329/1222038140823539875

**Comment by dyceron** [comment]
Could probably make a class for this or some mapping to make this not be bloated

**Comment by dyceron** [comment]
Would a class be overkill for this?

**Comment by ThanatosGit** [comment]
I guess a mapping is fine? Should be something like scenario -> list of pickup names -> list of cc groups it needs to be added

**Comment by dyceron** [comment]
I looked at the rest of Item Bomb blocks in the game and only two extra (four total) would be relevant.

`Area 1 - Temple Exterior` (cc18) can be broken from below from cc48. This is only possible if you lay the PB in the top left corner of the cc, so in 99% of cases this isn't an issue. This causes a visual bug similar to A2 so the same fix should be applied there.

And there's the one mentioned in this issue, which I'm currently unable to replicate, but it'd would likely get the same treatment as above.

**Comment by dyceron** [comment]
So I think the best plan here is to just do what was done in a2, since the connecting ccs are immediately accessible from the one where the pb is laid. Could do a simple grouping then
