### ISSUE TITLE
Alpha newborn can respawn

### ISSUE THREAD

**Issue by ThanatosGit** [randovania/open-samus-returns-rando#318]
Haven't tried to reproduce yet but it was something like:
- "backdoored" alpha newborn
- much later in the seed came back again via backdoor
- alpha spawned again after triggering for the first time the melee tutorial thing next to the missile block

**Comment by dyceron** [comment]
By Melee Tutorial, where is this? In the same cc as the Alpha or somewhere else?

**Comment by dyceron** [comment]
Replicated. Will look into it.
