### ISSUE TITLE
Crystal Caves - Mines Intersection Terminal door is blocked by something in Door Lock

### ISSUE THREAD

**Issue by dyceron** [randovania/open-samus-returns-rando#345]
https://discord.com/channels/914291389293027329/1239860131659907082

**Comment by dyceron** [comment]
The blockage randomly goes away after entering the start of the chase rooms. Too door has been excluded from shuffle until this is solved.

**Comment by dyceron** [comment]
Edit the bmscd for s050_area5

**Comment by Miepee** [comment]
![grafik](https://github.com/randovania/open-samus-returns-rando/assets/38186597/fbb8af5d-60ba-464b-b088-165764e6a283)
