### ISSUE TITLE
Diggernaut PB Disable not covering all cases

### ISSUE THREAD

**Issue by dyceron** [randovania/open-samus-returns-rando#348]
If you start the fight, then reload to checkpoint and use a pb before reentering the fight, pbs are "disabled" but can still be used in the fight.

**Comment by ThanatosGit** [comment]
Geez, if you are doing that now:
> I played around with it earlier and I was able to also do it with max pbs. It's just morph and hold R while going through the door.
 you are not able to use your normal bombs anymore. I can use them with a couple of frames when morphing.

**Comment by dyceron** [comment]
What really? Sounds like something we can't prevent for Bombs.

**Comment by ThanatosGit** [comment]
I know, I have no input display but I just spammed the fire button while being morphed and it only works during the morph animation for one bomb:

https://github.com/randovania/open-samus-returns-rando/assets/117127188/4d187094-b390-4609-a722-fcbc225fd1f0
