### ISSUE TITLE
Suits, Aeion Abilities, and the Baby require a reload to be visible/use

### ISSUE THREAD

**Issue by dyceron** [randovania/open-samus-returns-rando#40]

**Comment by duncathan** [comment]
this is probably going to need the same fix(es) as dread did

**Comment by ThanatosGit** [comment]
Is this still the case for Aeion? The others are fixed afaik

**Comment by dyceron** [comment]
It depends on the template bmsad used iirc

**Comment by dyceron** [comment]
The Baby is not as issue as of #72

**Comment by dyceron** [comment]
Suits have been fixed as of #64 and #67

**Comment by dyceron** [comment]
Baby still seems to be broken

**Comment by ThanatosGit** [comment]
A little bit more specific please :p

Afaik all test jsons for the models still work. Is it a specific area, location or state?

**Comment by dyceron** [comment]
Baby on a non custom actor doesn't spawn it in. So far tested on the etank before charge beam in surface.

**Comment by ThanatosGit** [comment]
Could be morph state then? Iirc samus morphed and unmorphed are two different things. Maybe the hatchling component doesn't exist on the morphed variant.

**Comment by dyceron** [comment]
I tested non morphed (with cheats) and it was also tested with morph

**Comment by ThanatosGit** [comment]
Best answer always: Works for me


https://github.com/randovania/open-samus-returns-rando/assets/117127188/4156276c-9427-41e1-9851-033e859fb51c
