### ISSUE TITLE
Some items are invisible

### ISSUE THREAD

**Issue by dyceron** [randovania/open-samus-returns-rando#45]
![image](https://github.com/randovania/open-samus-returns-rando/assets/38679103/f67d8464-55f2-4731-85a0-88490ba40bb4)

**Comment by Miepee** [comment]
Technically this is more "items have wrong position/scale" rather than "invisible"

**Comment by dyceron** [comment]
I haven't looked at this again. I need to see if this was a fluke.

**Comment by dyceron** [comment]
Upon further testing, this indeed is a height issue. Tested a few items there, and so far High Junp and Plasma are invisible. I'll have to look into how to make those models smaller. Might also be a reason why #8 is happening.

**Comment by dyceron** [comment]
Seems like this issue wasn't fully resolved. This is the second instance in one seed where items are invisible. The first occurred with the item at the top of `s065_area6b` which was a Progressive Suit. It was invisible when I first saw in then when I dropped to the left side of the room then went back up it suddenly appeared.

![image](https://github.com/randovania/open-samus-returns-rando/assets/38679103/85390067-2a08-4f60-9d8b-d9e409405990)

**Comment by ThanatosGit** [comment]
Is it easy to reproduce that way?
Does this include any changes for the doors, we were talking about it? If not, does this happen without any change to doors?

**Comment by dyceron** [comment]
I didn't get a chance to mess with the doors, so this is just with the current state.

**Comment by dyceron** [comment]
Commenting out the door patches file does not have an effect. It looks like this is only affecting progressives, specifically jump and suit. Beam seems to be unaffected.

**Comment by dyceron** [comment]
Another instance of this bug ![image](https://github.com/randovania/open-samus-returns-rando/assets/38679103/1e80322c-b3d1-409c-80c4-4ec69d3d8132)

**Comment by ThanatosGit** [comment]
I'm lazy: Please send a patcher json file (bonus points for starting at the nearest point) 😝

**Comment by dyceron** [comment]
The one used for the Gamma test has the issue. Just head to area 2c Lightning armor room

**Comment by ThanatosGit** [comment]
Uh, well Ok the Progressive Jump is an oversight by me. There is no model assigned if you already have all items of the progression stage. I fixed that locally.
But that does not apply to the Plasma Beam at the top of the room because the patcher file only includes wave and spazer as items.

**Comment by ThanatosGit** [comment]
Is the plasma beam only invisible if you don't collect the jump? Because it was always visible for me but had no cheat active to go through the walls

**Comment by dyceron** [comment]
I'm not sure. I used the input file but changed my spawn so I came into that room from the entrance so I saw Jump first. Plasma was invisible when I reached it after collecting jump

**Comment by dyceron** [comment]
Oh actually I mightve had Plasma by then?

**Comment by ThanatosGit** [comment]
Maybe.

**Comment by ThanatosGit** [comment]
> Edit: I collected the Screw Attack locked item in Area 5 Exterior and then Progressive Suit (top of the same room) suddenly appeared. Something weird is going on.

This still sounds unrelated to my fix but if this happens again, please send a patcher json and nearest start point :p

**Comment by dyceron** [comment]
3rd times the charm, right? 🙃
