### ISSUE TITLE
Keep Fleech Swarms active even after collecting Gravity Suit

### ISSUE THREAD

**Issue by dyceron** [randovania/open-samus-returns-rando#46]
After collecting Gravity Suit, if a scenario has Fleech Swarm, they get disabled. If you collect Gravity in the same scenario that has Fleech Swarm, they remain active, but when in contact, they latch onto Samus dealing no damage, and then the Hive deactivates

**Comment by Miepee** [comment]
rip the 5 people who know about mechanism

**Comment by dyceron** [comment]
Since Lightning Armor has a lot more uses now, not doing this is good for balancing Gravity to have more uses besides just water.
