### ISSUE TITLE
DNA in auto tracker

### ISSUE THREAD

**Issue by ThanatosGit** [randovania/open-samus-returns-rando#468]
@dyceron what are we gonna do with the DNA in the auto tracker? In the game + in the future we will count down from the required DNA to 0.
We could also place more than 39 DNA.

Should we make it consistent and also just show the DNA left in the game or are we going to count up from "collected dna / required dna" ?
The latter could also mean we are doing nothing until we support placing more than 39 DNA officially.

**Comment by dyceron** [comment]
Probably easier just keep it counting up. Probably should remove the `/39` part though, and also have it not count starting dna.

**Comment by dyceron** [comment]
Probably easier just keep it counting up. Probably should remove the `/39` part though, and also have it not count starting dna.

**Comment by dyceron** [comment]
Could the tracker list something like `0/10`, where the 10 is the required DNA? I don't think that'd be bad.

**Comment by dyceron** [comment]
Then let's do that. It's the most intuitive to me.
