### ISSUE TITLE
Collecting Gravity Suit Underwater/Underlava does not remove liquid effect

### ISSUE THREAD

**Issue by dyceron** [randovania/open-samus-returns-rando#62]
This is a major bug because reloading to save directly causes the effect to be permanent until you restart the game.

A temporary solution until #13 is fixed is to reload from checkpoint first which does remove the effect, but this is not ideal.

**Comment by ThanatosGit** [comment]
At least the lava one is fixable by calling: `Game.GetEntity("Lava_Trigger_001").TRIGGER:DisableTrigger()` before granting Gravity.

`HiddenPowerup002` in Trigger zone of `Lava_Trigger_001`  in `s010_area1`

The water one needs to be tested should be:
`LE_Item_004` in Trigger zone of `TG_SP_Water_002` in `s067_area6c`
