### ISSUE TITLE
Pre-Chozo Seal activation collision_cameras activate when returning all DNA for an area

### ISSUE THREAD

**Issue by dyceron** [randovania/open-samus-returns-rando#85]
I haven't tested every area, but this does happen in Surface, so I suspect that the collision_cameras weren't disabled properly.

**Comment by ThanatosGit** [comment]
I have no idea what this issue is actually about 🤔
You return all DNA and what actually changes then? 
Is this really an issue if we want to disable the option to activate the seals at all?

**Comment by dyceron** [comment]
Turns out it also applies if you have "awakened" the seal and then have the correct amount of DNA to unlock it this happens. Regardless, the hud count should be changed to be dna count / total dna required instead of dna count / required dna for seal

**Comment by ThanatosGit** [comment]
Uh, now I'm even more confused. What does change?
And the second part sounds like a complete different issue / qol feature

**Comment by dyceron** [comment]
> Is this really an issue if we want to disable the option to activate the seals at all?

Technically it's not an issue, no. For a first release goal, ideally we disable the dna check and just have it display a message that would be used for hints and be changed accordingly when the platform is used. As for recording the hint somewhere so it can viewed in the phase screen or map idk

**Comment by dyceron** [comment]
> Uh, now I'm even more confused. What does change?

Each chozo seal CC has 3 ccs technically, the top half above the seal, the bottom one below the seal, and then the combined one for after the seal is used. Having the correct amount of DNA changes the active cc to the split ones from the combined one.

**Comment by ThanatosGit** [comment]
Does this reenable the purple liquid or basically removes all enemies from below the seal?

**Comment by dyceron** [comment]
It only changes the cameras.

**Comment by ThanatosGit** [comment]
Oh ok. Like it is aligned to the top?

**Comment by dyceron** [comment]
No it just loads the two split cameras instead as if the acid were there still, so dropping below the seal jolts the camera to the 2nd cc and vice versa

**Comment by dyceron** [comment]
I've only experienced this in Surface so maybe it has to do with killing the Alpha and not having DNA.

https://github.com/randovania/open-samus-returns-rando/assets/38679103/d916f32b-b31a-4a99-a7cf-ffd6b1e77fd4
